Repository habx/apollo-multi-endpoint-link, pull requests merged in 2020-08, with the labels that each got.

#53 APP-13282: AC3
  package-lock.json
  package.json
  src/MultiAPILink.ts
Labels: habx-automerge, habx-autorelease-major

#56 APP-13335: add getContext param
  README.md
  package-lock.json
  src/MultiAPILink.ts
Labels: habx-automerge, habx-autorelease

#58 Fixed an issue in request function
  src/MultiAPILink.ts
Labels: habx-autorelease
